import Head from 'next/head'
import CardPost from '../components/CardPost'
import Header from '../components/Header'

export default function Home({post}) {
  return (
    <div className="max-w-screen-sm">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* main section */}
      <div className='px-3 py-4 mt-4'>
        <CardPost post={post}/>
      </div>
      {/* main section */}


    </div>
  )
}


export const getServerSideProps = async() => {
  const response = await fetch('https://6348e8910b382d796c79d0c7.mockapi.io/post');
  const data = await response.json();
  console.log(data);
  return {
    props : {
      post : data
    }
  }
}